---
- hosts: all
  gather_facts: no

  tasks:
    - name: Running apt update
      ansible.builtin.package:
        update_cache:yes

    - name: Installing required packages
      ansible.builtin.package: name={{item}} state=present
      with_items:
       - fail2ban
       - postgresql
       - postgresql-client
       - git
       - python3-pip
      #  - rdiff-backup
      #  - libpq-dev
       - python3-psycopg2
       - uwsgi
       - uwsgi-plugin-python3
       - nginx
